language: node_js

sudo: required
dist: xenial

node_js: stable

#install:
#  - npm install

branches:
  only:
    - hexo

before_install: 
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli
#  - sudo apt-get install libpng16-dev
install:
  - npm install

script:
  - hexo clean
  - hexo generate
  # - hexo deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  target-branch: master
  on:
    branch: hexo